name: LMS CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      MONGO_URI: ${{secrets.MONGO_URI}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci
      - name: Start server
        run: node index.js
